#!name=QQ音乐成长值签到
#!desc=自动获取QQ音乐签到凭证并执行每日签到

^https:\/\/u6\.y\.qq\.com\/cgi-bin\/musics\.fcg(?=[^#]*[?&]_webcgikey=EveryDaySignLvzScore(?:&|$))[^#]*$ url script-request-body https://raw.githubusercontent.com/XHSCF/qqmusic-qx-checkin/main/qqmusic_capture.js

hostname = u6.y.qq.com

# 定时任务示例：每天08:20执行
# 20 8 * * * https://raw.githubusercontent.com/XHSCF/qqmusic-qx-checkin/main/qqmusic_checkin.js, tag=QQ音乐成长值签到, enabled=true
